package com.txws.model;

// Generated 2014-8-13 11:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserTable generated by hbm2java
 */
@Entity
@Table(name="user_table")
public class UserTable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8340159069405657200L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="user_id")
	private Integer userId;
	@Column(name="user_name")
	private String userName;
	@Column(name="user_pw")
	private String userPw;
	@Column(name="user_ico")
	private String userIco;
	@Column(name="sex")
	private String sex;
	@Column(name="birth")
	private Date birth;
	@Column(name="folk")
	private String folk;
	@Column(name="politice_status")
	private String politiceStatus;
	@Column(name="id")
	private String id;
	@Column(name="tel")
	private String tel;
	@Column(name="college")
	private String college;
	@Column(name="degree")
	private String degree;
	@Column(name="major")
	private String major;
	@Column(name="time_of_work")
	private Date timeOfWork;
	@Column(name="dep")
	private String dep;
	@Column(name="current_dep")
	private String currentDep;
	@Column(name="posi_level")
	private String posiLevel;
	@Column(name="posi")
	private String posi;
	@Column(name="duty_scope")
	private String dutyScope;
	@Column(name="duty")
	private String duty;
	@Column(name="time_in_poi")
	private Date timeInPoi;
	@Column(name="contract")
	private String contract;
	@Column(name="insurance")
	private String insurance;
	@Column(name="personnel_status_change")
	private Date personnelStatusChange;
	@Column(name="personnel_status")
	private String personnelStatus;
	@Column(name="personnel_type")
	private String personnelType;
	@Column(name="grant_type")
	private String grantType;
	@Column(name="checkingIn_status")
	private Integer checkingInStatus;
	@Column(name="role_id")
	private int roleId;
	@Column(name="remarks")
	private String remarks;
	@Column(name="user_no")
	private String userNo;
	
	public UserTable() {
		super();
	}

	public UserTable(Integer userId, String userName, String userPw,
			String userIco, String sex, Date birth, String folk,
			String politiceStatus, String id, String tel, String college,
			String degree, String major, Date timeOfWork, String dep,
			String currentDep, String posiLevel, String posi, String dutyScope,
			String duty, Date timeInPoi, String contract, String insurance,
			Date personnelStatusChange, String personnelStatus,
			String personnelType, String grantType, Integer checkingInStatus,
			int roleId, String remarks, String userNo) {
		super();
		this.userId = userId;
		this.userName = userName;
		this.userPw = userPw;
		this.userIco = userIco;
		this.sex = sex;
		this.birth = birth;
		this.folk = folk;
		this.politiceStatus = politiceStatus;
		this.id = id;
		this.tel = tel;
		this.college = college;
		this.degree = degree;
		this.major = major;
		this.timeOfWork = timeOfWork;
		this.dep = dep;
		this.currentDep = currentDep;
		this.posiLevel = posiLevel;
		this.posi = posi;
		this.dutyScope = dutyScope;
		this.duty = duty;
		this.timeInPoi = timeInPoi;
		this.contract = contract;
		this.insurance = insurance;
		this.personnelStatusChange = personnelStatusChange;
		this.personnelStatus = personnelStatus;
		this.personnelType = personnelType;
		this.grantType = grantType;
		this.checkingInStatus = checkingInStatus;
		this.roleId = roleId;
		this.remarks = remarks;
		this.userNo = userNo;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public String getUserIco() {
		return userIco;
	}

	public void setUserIco(String userIco) {
		this.userIco = userIco;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirth() {
		return birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	public String getFolk() {
		return folk;
	}

	public void setFolk(String folk) {
		this.folk = folk;
	}

	public String getPoliticeStatus() {
		return politiceStatus;
	}

	public void setPoliticeStatus(String politiceStatus) {
		this.politiceStatus = politiceStatus;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getCollege() {
		return college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public String getDegree() {
		return degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getMajor() {
		return major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public Date getTimeOfWork() {
		return timeOfWork;
	}

	public void setTimeOfWork(Date timeOfWork) {
		this.timeOfWork = timeOfWork;
	}

	public String getDep() {
		return dep;
	}

	public void setDep(String dep) {
		this.dep = dep;
	}

	public String getCurrentDep() {
		return currentDep;
	}

	public void setCurrentDep(String currentDep) {
		this.currentDep = currentDep;
	}

	public String getPosiLevel() {
		return posiLevel;
	}

	public void setPosiLevel(String posiLevel) {
		this.posiLevel = posiLevel;
	}

	public String getPosi() {
		return posi;
	}

	public void setPosi(String posi) {
		this.posi = posi;
	}

	public String getDutyScope() {
		return dutyScope;
	}

	public void setDutyScope(String dutyScope) {
		this.dutyScope = dutyScope;
	}

	public String getDuty() {
		return duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public Date getTimeInPoi() {
		return timeInPoi;
	}

	public void setTimeInPoi(Date timeInPoi) {
		this.timeInPoi = timeInPoi;
	}

	public String getContract() {
		return contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	public String getInsurance() {
		return insurance;
	}

	public void setInsurance(String insurance) {
		this.insurance = insurance;
	}

	public Date getPersonnelStatusChange() {
		return personnelStatusChange;
	}

	public void setPersonnelStatusChange(Date personnelStatusChange) {
		this.personnelStatusChange = personnelStatusChange;
	}

	public String getPersonnelStatus() {
		return personnelStatus;
	}

	public void setPersonnelStatus(String personnelStatus) {
		this.personnelStatus = personnelStatus;
	}

	public String getPersonnelType() {
		return personnelType;
	}

	public void setPersonnelType(String personnelType) {
		this.personnelType = personnelType;
	}

	public String getGrantType() {
		return grantType;
	}

	public void setGrantType(String grantType) {
		this.grantType = grantType;
	}

	public Integer getCheckingInStatus() {
		return checkingInStatus;
	}

	public void setCheckingInStatus(Integer checkingInStatus) {
		this.checkingInStatus = checkingInStatus;
	}

	public int getRoleId() {
		return roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getUserNo() {
		return userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

}
